In [4]:
import pandas as pd
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from string import ascii_letters
import numpy as np
import pandas as pd
import seaborn as sns
#!pip install imbalanced-learn
#!pip3 install -U imbalanced-learn
from imblearn.over_sampling import SMOTE
import imblearn
import time
from os.path import getsize
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier
from sklearn import tree
import pickle

# from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor


In [3]:
loan_df = pd.read_csv("../Resources/accepted2.csv")

In [5]:
loan_df1 = loan_df.drop(["mths_since_last_delinq","mths_since_last_record","dti_joint","annual_inc_joint","zip_code","addr_state","title"], axis=1)



In [6]:
loan_df2 = loan_df1.dropna()


In [7]:
loan_df3 = loan_df2[["recoveries","total_rec_late_fee","total_rec_prncp","delinq_2yrs","fico_range_high","loan_status","total_pymnt"]]



In [8]:
loan_df3["loan_status"].value_counts()

Fully Paid            39297
Current               29528
Charged Off            9788
Late (31-120 days)      702
In Grace Period         290
Late (16-30 days)       136
Default                   1
Name: loan_status, dtype: int64

In [9]:
loan_df4 = loan_df3.apply(lambda x: x.mask(x.map(x.value_counts())<= 9788, 'Late') if x.name=='loan_status' else x)

loan_df5 = loan_df4.apply(lambda x: x.mask(x.map(x.value_counts())>= 29528, 'Fully Paid') if x.name=='loan_status' else x)


In [10]:
loan_df5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79742 entries, 0 to 106996
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   recoveries          79742 non-null  float64
 1   total_rec_late_fee  79742 non-null  float64
 2   total_rec_prncp     79742 non-null  float64
 3   delinq_2yrs         79742 non-null  float64
 4   fico_range_high     79742 non-null  int64  
 5   loan_status         79742 non-null  object 
 6   total_pymnt         79742 non-null  float64
dtypes: float64(5), int64(1), object(1)
memory usage: 4.9+ MB


In [11]:
dummies_df = pd.get_dummies(loan_df5)

dummies_df.to_csv("status_predictor.csv")

dummies_df

recoveries  total_rec_late_fee  total_rec_prncp  delinq_2yrs  \
0              0.0                0.00          6500.00          0.0   
1              0.0                0.00           924.75          0.0   
2              0.0                0.00         20000.00          0.0   
4              0.0               28.92         18097.94          0.0   
5              0.0                0.00          4208.19          0.0   
...            ...                 ...              ...          ...   
106991         0.0                0.00         10000.00          0.0   
106992         0.0                0.00          1995.32          0.0   
106993         0.0                0.00          1791.46          0.0   
106994         0.0                0.00          2822.96          0.0   
106996         0.0                0.00         12000.00          0.0   

        fico_range_high  total_pymnt  loan_status_Fully Paid  loan_status_Late  
0                   679   6786.02000                       1                 0  
1                   699   1105.76000                       1                 0  
2                   694  22974.52785                       1                 0  
4                   669  28350.71000                       1                 0  
5                   724   6826.83000                       1                 0  
...                 ...          ...                     ...               ...  
106991              689  11879.68359                       1                 0  
106992              729   3059.21000                       1                 0  
106993              684   2150.89000                       1                 0  
106994              684   3928.47000                       1                 0  
106996              754  12991.80918                       1                 0  

[79742 rows x 8 columns]

# Logistic Regression

In [12]:
from sklearn.model_selection import train_test_split
# X = train_df
X = dummies_df.drop(["loan_status_Fully Paid","loan_status_Late"], axis=1)

y = dummies_df["loan_status_Fully Paid"]

oversample = SMOTE()

X, y = oversample.fit_resample(X, y)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)


In [33]:
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [34]:
filename = '../Models/loan_status_scaler.sav'
pickle.dump(scaler, open(filename, 'wb'))

In [14]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier

classifier.fit(X_train_scaled, y_train)

#logistic regression
print(f'Training Score: {classifier.score(X_train_scaled, y_train)}')
print(f'Testing Score: {classifier.score(X_test_scaled, y_test)}')

Training Score: 0.8408128868525819
Testing Score: 0.8451166710254846


In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


y_true = y_test

y_pred = classifier.predict(X_test)

confusion_matrix(y_true, y_pred)

confusion_matrix(y_test, y_pred)

/Users/andrealynnbaker/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([[14202,  2848],
       [ 3349, 14014]])

In [16]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_true, y_pred)


0.8200402311653712

In [17]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred, target_names=["Late","Fully Paid"]))

              precision    recall  f1-score   support

        Late       0.81      0.83      0.82     17050
  Fully Paid       0.83      0.81      0.82     17363

    accuracy                           0.82     34413
   macro avg       0.82      0.82      0.82     34413
weighted avg       0.82      0.82      0.82     34413



In [18]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

In [17]:
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
    'weights': ['uniform', 'distance'],
    'leaf_size': [10, 50, 100, 500]
}
grid_clf = GridSearchCV(model, param_grid, verbose=3)

In [18]:
grid_clf.fit(X_train, y_train)

Fitting 5 folds for each of 80 candidates, totalling 400 fits
[CV 1/5] END leaf_size=10, n_neighbors=1, weights=uniform;, score=0.910 total time=   1.3s
[CV 2/5] END leaf_size=10, n_neighbors=1, weights=uniform;, score=0.910 total time=   1.1s
[CV 3/5] END leaf_size=10, n_neighbors=1, weights=uniform;, score=0.912 total time=   1.1s
[CV 4/5] END leaf_size=10, n_neighbors=1, weights=uniform;, score=0.914 total time=   1.2s
[CV 5/5] END leaf_size=10, n_neighbors=1, weights=uniform;, score=0.911 total time=   1.1s
[CV 1/5] END leaf_size=10, n_neighbors=1, weights=distance;, score=0.910 total time=   0.3s
[CV 2/5] END leaf_size=10, n_neighbors=1, weights=distance;, score=0.910 total time=   0.3s
[CV 3/5] END leaf_size=10, n_neighbors=1, weights=distance;, score=0.912 total time=   0.3s
[CV 4/5] END leaf_size=10, n_neighbors=1, weights=distance;, score=0.914 total time=   0.3s
[CV 5/5] END leaf_size=10, n_neighbors=1, weights=distance;, score=0.911 total time=   0.3s
[CV 1/5] END leaf_size=

[CV 5/5] END leaf_size=10, n_neighbors=17, weights=distance;, score=0.896 total time=   0.6s
[CV 1/5] END leaf_size=10, n_neighbors=19, weights=uniform;, score=0.861 total time=   1.3s
[CV 2/5] END leaf_size=10, n_neighbors=19, weights=uniform;, score=0.862 total time=   1.6s
[CV 3/5] END leaf_size=10, n_neighbors=19, weights=uniform;, score=0.861 total time=   1.4s
[CV 4/5] END leaf_size=10, n_neighbors=19, weights=uniform;, score=0.866 total time=   1.3s
[CV 5/5] END leaf_size=10, n_neighbors=19, weights=uniform;, score=0.863 total time=   1.3s
[CV 1/5] END leaf_size=10, n_neighbors=19, weights=distance;, score=0.891 total time=   0.6s
[CV 2/5] END leaf_size=10, n_neighbors=19, weights=distance;, score=0.891 total time=   0.7s
[CV 3/5] END leaf_size=10, n_neighbors=19, weights=distance;, score=0.890 total time=   0.8s
[CV 4/5] END leaf_size=10, n_neighbors=19, weights=distance;, score=0.897 total time=   0.5s
[CV 5/5] END leaf_size=10, n_neighbors=19, weights=distance;, score=0.895 t

[CV 5/5] END leaf_size=50, n_neighbors=15, weights=distance;, score=0.897 total time=   0.7s
[CV 1/5] END leaf_size=50, n_neighbors=17, weights=uniform;, score=0.864 total time=   1.4s
[CV 2/5] END leaf_size=50, n_neighbors=17, weights=uniform;, score=0.864 total time=   1.4s
[CV 3/5] END leaf_size=50, n_neighbors=17, weights=uniform;, score=0.863 total time=   1.4s
[CV 4/5] END leaf_size=50, n_neighbors=17, weights=uniform;, score=0.867 total time=   1.4s
[CV 5/5] END leaf_size=50, n_neighbors=17, weights=uniform;, score=0.866 total time=   1.4s
[CV 1/5] END leaf_size=50, n_neighbors=17, weights=distance;, score=0.892 total time=   0.7s
[CV 2/5] END leaf_size=50, n_neighbors=17, weights=distance;, score=0.891 total time=   0.7s
[CV 3/5] END leaf_size=50, n_neighbors=17, weights=distance;, score=0.893 total time=   0.7s
[CV 4/5] END leaf_size=50, n_neighbors=17, weights=distance;, score=0.898 total time=   0.7s
[CV 5/5] END leaf_size=50, n_neighbors=17, weights=distance;, score=0.896 t

[CV 4/5] END leaf_size=100, n_neighbors=13, weights=distance;, score=0.900 total time=   0.7s
[CV 5/5] END leaf_size=100, n_neighbors=13, weights=distance;, score=0.898 total time=   0.9s
[CV 1/5] END leaf_size=100, n_neighbors=15, weights=uniform;, score=0.867 total time=   1.6s
[CV 2/5] END leaf_size=100, n_neighbors=15, weights=uniform;, score=0.864 total time=   1.8s
[CV 3/5] END leaf_size=100, n_neighbors=15, weights=uniform;, score=0.866 total time=   1.7s
[CV 4/5] END leaf_size=100, n_neighbors=15, weights=uniform;, score=0.869 total time=   1.8s
[CV 5/5] END leaf_size=100, n_neighbors=15, weights=uniform;, score=0.868 total time=   3.2s
[CV 1/5] END leaf_size=100, n_neighbors=15, weights=distance;, score=0.894 total time=   1.5s
[CV 2/5] END leaf_size=100, n_neighbors=15, weights=distance;, score=0.893 total time=   1.7s
[CV 3/5] END leaf_size=100, n_neighbors=15, weights=distance;, score=0.895 total time=   0.9s
[CV 4/5] END leaf_size=100, n_neighbors=15, weights=distance;, sc

[CV 3/5] END leaf_size=500, n_neighbors=11, weights=distance;, score=0.897 total time=   1.7s
[CV 4/5] END leaf_size=500, n_neighbors=11, weights=distance;, score=0.901 total time=   1.6s
[CV 5/5] END leaf_size=500, n_neighbors=11, weights=distance;, score=0.900 total time=   1.8s
[CV 1/5] END leaf_size=500, n_neighbors=13, weights=uniform;, score=0.869 total time=   2.6s
[CV 2/5] END leaf_size=500, n_neighbors=13, weights=uniform;, score=0.867 total time=   3.0s
[CV 3/5] END leaf_size=500, n_neighbors=13, weights=uniform;, score=0.868 total time=   2.9s
[CV 4/5] END leaf_size=500, n_neighbors=13, weights=uniform;, score=0.873 total time=   2.6s
[CV 5/5] END leaf_size=500, n_neighbors=13, weights=uniform;, score=0.870 total time=   2.8s
[CV 1/5] END leaf_size=500, n_neighbors=13, weights=distance;, score=0.895 total time=   2.1s
[CV 2/5] END leaf_size=500, n_neighbors=13, weights=distance;, score=0.895 total time=   1.9s
[CV 3/5] END leaf_size=500, n_neighbors=13, weights=distance;, sc

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [10, 50, 100, 500],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [19]:
print(grid_clf.best_params_)

{'leaf_size': 10, 'n_neighbors': 1, 'weights': 'uniform'}


In [20]:
print(grid_clf.best_score_)

0.9114658803964509


In [21]:
grid_clf

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [10, 50, 100, 500],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [22]:
y_true = y_test

y_pred = grid_clf.predict(X_test)

confusion_matrix(y_true, y_pred)

confusion_matrix(y_test, y_pred)

array([[16028,  1022],
       [ 1796, 15567]])

In [ ]:


model = grid_clf

filename = 'loan_status_predictor.sav'
pickle.dump(model, open(filename, 'wb'))

In [19]:
data = [X_train_scaled, X_test_scaled, y_train, y_test]

In [20]:


def test_classification_model(model, data, folder, savePickle=False):
    from time import time
    
    start = time()
    X_train_scaled, X_test_scaled, y_train, y_test = data

    reg = model.fit(X_train_scaled, y_train)
    print(f'Model: {type(reg).__name__}')
    print(f'Train score: {reg.score(X_train_scaled, y_train)}')
    print(f'Test Score: {reg.score(X_test_scaled, y_test)}\n')
#     plt.show()    
    y_true = y_test
    y_pred = model.predict(X_test_scaled)
    print('Confusion Matrix:\n',confusion_matrix(y_true, y_pred), '\n\n')
    confusion_score(y_true, y_pred)
    end = time()
#   This section pertains to pickling the model
    if(savePickle):
        filename = f'{folder}/{type(reg).__name__}.sav'
        pickle.dump(model, open(filename, 'wb'))
        print(f'{getsize(filename):,} bytes')

    
    
    filename = f'{folder}/{type(reg).__name__}.sav'
    #pickle.dump(model, open(filename, 'wb'))
    print(f'{getsize(filename):,} bytes')
    
    print('~'*80)
    
#     return(y_true, y_pred)
    
    
    
def confusion_score(y_true, y_pred):
    from sklearn.metrics import confusion_matrix
    [[TP, FN],[FP,TN]] = confusion_matrix(y_true, y_pred)

    accuracy = round((TP + TN) / (TP + FP + TN + FN),4) # (111 + 128) / (111 + 5 + 128 + 6)
#     print(f"Accuracy: {accuracy.round(4)}")
    precision = round((TP / (TP + FP)),4)
#     print(f'Precision: {precision.round(4)}')
    sensitivity = round(TP / (TP + FN),4)
#     print(f'Sensitivity: {sensitivity.round(4)}')
    specificity = round(TN / (TN + FP),4)
#     print(f'Specificity: {specificity.round(4)}')

    neg_predictive_value = round(TN / (TN + FN),4)
    
    matrix = [
#         ['','Predicted Class','Predicted Class',''],
        ['CONFUSION','Pred. Pos.','Pred. Neg.',''],
        ['MATRIX','_'*50],
        ['Act. Positive',TP,FN,sensitivity,'sensitivity'],
        ['Act. Negative',FP,TN,specificity,'specificity'],
        ['',precision,neg_predictive_value,accuracy,'accuracy'],
        ['','precision','neg. pred. value']
    ]
    
    for i in matrix:
        for j in i:
            print(f'{j:^16}|', end='')
        print("")
        
        
        
        
# IN CASE OF 3x3 CONFUSION MATRIX:

def confusion_score2(y_true, y_pred):
    from sklearn.metrics import confusion_matrix
    [[a1, a2, a3],[b1,b2, b3],[c1,c2,c3]] = confusion_matrix(y_true, y_pred)
    TP = a1
    FN = a2 + a3
    FP = b1 + c1
    TN = b2 + b3 + c2 + c3

    accuracy = (TP + TN) / (TP + FP + TN + FN) # (111 + 128) / (111 + 5 + 128 + 6)
    print(f"Accuracy: {accuracy.round(3)}")
    precision = TP / (TP + FP)
    print(f'Precision: {precision.round(3)}')
    sensitivity = TP / (TP + FN)
    print(f'Sensitivity: {sensitivity.round(3)}')
    specificity = TN / (TN + FP)
    print(f'Specificity: {specificity.round(3)}')

In [26]:
# multiple classification tests

# test_model(LinearRegression(), data)

test_list = [    
    LogisticRegression(),
    #RandomForestClassifier(random_state=1, n_estimators=100),
    #tree.DecisionTreeClassifier(),
    KNeighborsClassifier(leaf_size= 10, n_neighbors= 1, weights= 'uniform'),
    #RandomForestClassifier(),
    #ExtraTreesClassifier(),
    AdaBoostClassifier()
]

folder = '../Models/status_model_save'

# test_model(LogisticRegression(),data)
#with ProcessPoolExecutor() as executor:

for model in test_list:

    try:

        # Don't pickle models
        test_classification_model(model, data, folder)
        # Pickle models
        # test_classification_model(model, data, folder, savePickle=True)    

        # test_model(SVR(C=1.0, epsilon=0.2), data)
    except Exception as e:
        print('#'*40)
        print('Exception found.')
        print(e)
        print('#'*40)
print('Done!')

Model: LogisticRegression
Train score: 0.8408128868525819
Test Score: 0.8451166710254846

Confusion Matrix:
 [[13060  3990]
 [ 1340 16023]] 


   CONFUSION    |   Pred. Pos.   |   Pred. Neg.   |                |
     MATRIX     |__________________________________________________|
 Act. Positive  |     13060      |      3990      |     0.766      |  sensitivity   |
 Act. Negative  |      1340      |     16023      |     0.9228     |  specificity   |
                |     0.9069     |     0.8006     |     0.8451     |    accuracy    |
                |   precision    |neg. pred. value|
Process time: 0.51 seconds.
744 bytes
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Model: KNeighborsClassifier
Train score: 0.9999903135503744
Test Score: 0.9219771597942638

Confusion Matrix:
 [[15672  1378]
 [ 1307 16056]] 


   CONFUSION    |   Pred. Pos.   |   Pred. Neg.   |                |
     MATRIX     |__________________________________________________|
 Act. P

In [30]:
# model = AdaBoostClassifier(base_estimator=KNeighborsClassifier(leaf_size= 10, n_neighbors= 1, weights= 'uniform' ))
# test_classification_model(model, data, folder)



ValueError: KNeighborsClassifier doesn't support sample_weight.